pinmark/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from bookmarks.views import *

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Browsing
    url(r'^$', main_page),
    url(r'^user/(?P<username>\w+)/$', user_page), # allow only alphanumeric character
    url(r'^tag/(?P<tag_name>\S+)/$', tag_page),   # any non-whitespace character is allowed
    url(r'^tag/$', tag_cloud_page),
    url(r'^search/$', search_page),

    # Ajax
    url(r'^ajax/tag/autocomplete/$', ajax_tag_autocomplete),

    # Session management
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', logout_page),
    url(r'^register/$', register_page),

    # Account management
    url(r'^save/$', bookmark_save_page),
    url(r'^vote/$', bookmark_vote_page),

]

bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User

class Link(models.Model):
    url = models.URLField(unique=True)

    def __str__(self):
        return  self.url

class Bookmark(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    link = models.ForeignKey(Link)

    def __str__(self):
        return '%s, %s' % (self.user.username, self.link.url)

class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)
    bookmarks = models.ManyToManyField(Bookmark)

    def __str__(self):
        return self.name

class SharedBookmark(models.Model):
    bookmark = models.OneToOneField(Bookmark)
    date = models.DateTimeField(auto_now_add=True)
    votes = models.IntegerField(default=1)
    users_voted = models.ManyToManyField(User)

    def __str__(self):
        return '%s, %s' % self.bookmark, self.votes

templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title>Django Bookmarks |
        {% block title %}{% endblock %}</title>
        {% block css %}
            <link rel="stylesheet"  type="text/css" href="{% static 'css/style.css' %}" />
        {% endblock %}
    </head>
    <body>
        <div id="nav">
            <a href="/">home</a> |
            {% if user.is_authenticated %}
                <a href="/save/">submit</a> |
                <a href="/search/">search</a> |
                welcome <a href="/user/{{ user.username }}">{{ user.username }}</a>
                (<a href="/logout">logout</a>)
            {% else %}
                <a href="/login/">login</a> |
                <a href="/register/">register</a>
            {% endif %}
        </div>

        <h1>{% block head %}{% endblock %}</h1>
        {% block content %}{% endblock %}

        {% block javascript %}
        <!-- Javascript code -->
        <script type="text/javascript" src="{% static 'js/jquery-1.11.3.js' %}"></script>
        {% endblock %}

    </body>
</html>

templates/bookmark_list.html
{% if bookmarks %}
    <ul class="bookmarks">
    {% for bookmark in bookmarks %}
        <li>
            <a href="{{ bookmark.link.url|escape }}" class="title">
                {{ bookmark.title|escape }}</a>
            {% if show_edit %}
                <a href="/save/?url={{ bookmark.link.url|urlencode }}"
                class="edit">[edit]</a>
            {% endif %}
            <br />
            {% if show_tags %}
                Tags:
                {% if bookmark.tag_set.all %}
                    <ul class="tags">
                    {% for tag in bookmark.tag_set.all %}
                        <li>
                            <a href="/tag/{{ tag.name|urlencode }}/">{{ tag.name|escape }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    None.
                {% endif %}
                <br />
            {% endif %}
            {% if show_user %}
                Posted by:
                <a href="/user/{{ bookmark.user.username }}/"
                class="username">
                {{ bookmark.user.username }}</a>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No bookmarks found.</p>
{% endif %}

templates/bookmark_save.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Save Bookmark{% endblock %}

{% block head %}Save Bookmark{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'vendor/jquery-autocomplete/jquery.autocomplete.css' %}" type="text/css" />
{% endblock %}

{% block content %}
    {% include 'bookmark_save_form.html' %}
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'vendor/jquery-autocomplete/lib/jquery.js' %}"> </script>
    <script type="text/javascript" src="{% static 'vendor/jquery-autocomplete/jquery.autocomplete.js' %}"> </script>
    <script type="text/javascript" src="{% static 'js/tag_autocomplete.js' %}"> </script>
{% endblock %}

templates/bookmark_save_form.html
<form id="save-form" method="post" action="/save/">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save" />
</form>

templates/main_page.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Welcome to Django Bookmarks{% endblock %}

{% block head %}Welcome to Django Bookmarks{% endblock %}

{% block content %}
    {% if user.username %}
        <p>Welcome {{ user.username }}!
        Here you can store and share bookmarks!</p>
    {% else %}
        <p>Welcome anonymous user!
        You need to <a href="/login/">login</a>
        before you can store and share bookmarks.</p>
    {% endif %}

    <h2>Bookmarks Shared by Users</h2>
    {% include 'shared_bookmark_list.html' %}

{% endblock %}

templates/search.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Search Bookmarks{% endblock %}
{% block head %}Search Bookmarks{% endblock %}
{% block content %}
<form id="search-form" method="get" action=".">
    {{ form.as_p }}
    <input type="submit" value="search" />
</form>

<div id="search-results">
    {% if show_results %}
        {% include 'bookmark_list.html' %}
    {% endif %}
</div>
{% endblock %}

{% block javascript %}
   {{ block.super }}
   <script type="text/javascript" src="{% static 'js/search.js' %}"></script>
{% endblock %}

templates/shared_bookmark_list.html
{% if shared_bookmarks %}
    <ul class="bookmarks">
        {% for shared_bookmark in shared_bookmarks %}
            <li>
                <a href="/vote/?id={{ shared_bookmark.id }}" class="vote">
                    [+]
                </a>

                <a href="{{ shared_bookmark.bookmark.link.url }}" class="title">
                    {{ shared_bookmark.bookmark.title|escape }}
                </a>
                <br />

                Posted By:
                <a href="/user/{{ shared_bookmark.bookmark.user.username }}/" class="username">
                    {{ shared_bookmark.bookmark.user.username }}
                </a> |

                <span class="vote-count">
                    Votes: {{ shared_bookmark.votes }}
                </span>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No bookmarks found.</p>
{% endif %}

templates/tag_cloud_page.html
{% extends "base.html" %}

{% block title %}Tag Cloud{% endblock %}

{% block head %}Tag Cloud{% endblock %}

{% block content %}
    <div id="tag-cloud">
        {% for tag in tags %}
            <a href="/tag/{{ tag.name|urlencode }}/"
            class="tag-cloud-{{ tag.weight }}">
            {{ tag.name|escape }}</a>
        {% endfor %}
    </div>
{% endblock %}

templates/tag_page.html
{% extends "base.html" %}

{% block title %}Tag: {{ tag_name|escape }}{% endblock %}

{% block head %}Bookmarks for tag: {{ tag_name|escape }}{% endblock %}

{% block content %}

   {% include "bookmark_list.html" %}

{% endblock %}

templates/user_page.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}{{ username }}{% endblock %}

{% block head %}Bookmarks for {{ username }}{% endblock %}

{% block content %}
    {% include "bookmark_list.html" %}
{% endblock %}

{% block javascript %}
   {{ block.super }}
   <script type="text/javascript" src="{% static 'js/bookmark_edit.js' %}"></script>
{% endblock %}